import { PrismaClient } from './generated'
import bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

const NIVEIS = [
  '6A', '5A', '4A', '3A', '2A', 'A', 'B', 'C', 'D',
  'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O'
]

async function main() {
  console.log('Iniciando seed...')

  // Matérias
  const materias = await Promise.all([
    prisma.materia.upsert({
      where: { codigo: 'MAT' },
      update: {},
      create: { nome: 'Matemática', codigo: 'MAT' },
    }),
    prisma.materia.upsert({
      where: { codigo: 'PORT' },
      update: {},
      create: { nome: 'Português', codigo: 'PORT' },
    }),
    prisma.materia.upsert({
      where: { codigo: 'ING' },
      update: {},
      create: { nome: 'Inglês', codigo: 'ING' },
    }),
  ])

  console.log(`Matérias criadas: ${materias.map(m => m.codigo).join(', ')}`)

  // Níveis para cada matéria
  for (const materia of materias) {
    for (let i = 0; i < NIVEIS.length; i++) {
      const codigo = NIVEIS[i] as string
      await prisma.nivel.upsert({
        where: { materiaId_codigo: { materiaId: materia.id, codigo } },
        update: {},
        create: {
          materiaId: materia.id,
          codigo,
          descricao: `Nível ${codigo} — ${materia.nome}`,
          ordem: i + 1,
        },
      })
    }
  }

  console.log(`Níveis criados: ${NIVEIS.length} por matéria`)

  // Usuário franqueado padrão
  const senhaHash = await bcrypt.hash('kumon@2024', 10)
  const franqueado = await prisma.usuario.upsert({
    where: { email: 'franqueado@kumonadvance.com' },
    update: {},
    create: {
      nome: 'Franqueado',
      email: 'franqueado@kumonadvance.com',
      senhaHash,
      perfil: 'franqueado',
    },
  })

  console.log(`Usuário franqueado criado: ${franqueado.email}`)

  // ─── Biblioteca de Exercícios — Seed inicial ─────────────────────────────────

  const bibExercicios = [
    // ── Matemática ──────────────────────────────────────────────────────────────
    {
      disciplina: 'matematica' as const,
      topico: 'Adição',
      subtopico: 'Adição simples',
      nivel: '4A',
      dificuldade: 'facil' as const,
      tipo: 'numerico' as const,
      enunciado: 'Quanto é 7 + 5?',
      opcoes: null,
      resposta: '12',
      explicacao: '7 + 5 = 12. Basta somar as duas parcelas.',
      tags: ['adição', 'básico', 'nível 4A'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },
    {
      disciplina: 'matematica' as const,
      topico: 'Adição',
      subtopico: 'Adição com reagrupamento',
      nivel: '3A',
      dificuldade: 'medio' as const,
      tipo: 'numerico' as const,
      enunciado: 'Resolva: 48 + 37 = ?',
      opcoes: null,
      resposta: '85',
      explicacao: '48 + 37: some as unidades (8+7=15, escreve 5 e vai 1) e as dezenas (4+3+1=8). Resultado: 85.',
      tags: ['adição', 'reagrupamento', 'nível 3A'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },
    {
      disciplina: 'matematica' as const,
      topico: 'Subtração',
      subtopico: 'Subtração simples',
      nivel: '4A',
      dificuldade: 'facil' as const,
      tipo: 'numerico' as const,
      enunciado: 'Calcule: 15 − 8 = ?',
      opcoes: null,
      resposta: '7',
      explicacao: '15 − 8 = 7. Subtraímos 8 de 15 e obtemos 7.',
      tags: ['subtração', 'básico'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },
    {
      disciplina: 'matematica' as const,
      topico: 'Multiplicação',
      subtopico: 'Tabuada do 6',
      nivel: 'B',
      dificuldade: 'facil' as const,
      tipo: 'numerico' as const,
      enunciado: 'Qual é o resultado de 6 × 8?',
      opcoes: null,
      resposta: '48',
      explicacao: '6 × 8 = 48. É a oitava entrada da tabuada do 6.',
      tags: ['multiplicação', 'tabuada', 'tabuada do 6'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },
    {
      disciplina: 'matematica' as const,
      topico: 'Multiplicação',
      subtopico: 'Multiplicação de dois dígitos',
      nivel: 'C',
      dificuldade: 'medio' as const,
      tipo: 'numerico' as const,
      enunciado: 'Calcule: 24 × 13 = ?',
      opcoes: null,
      resposta: '312',
      explicacao: '24 × 13 = 24 × 10 + 24 × 3 = 240 + 72 = 312.',
      tags: ['multiplicação', 'dois dígitos'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },
    {
      disciplina: 'matematica' as const,
      topico: 'Divisão',
      subtopico: 'Divisão exata',
      nivel: 'C',
      dificuldade: 'facil' as const,
      tipo: 'numerico' as const,
      enunciado: 'Quanto é 56 ÷ 7?',
      opcoes: null,
      resposta: '8',
      explicacao: '56 ÷ 7 = 8, pois 7 × 8 = 56.',
      tags: ['divisão', 'exata', 'tabuada'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },
    {
      disciplina: 'matematica' as const,
      topico: 'Frações',
      subtopico: 'Fração de um inteiro',
      nivel: 'D',
      dificuldade: 'medio' as const,
      tipo: 'objetivo' as const,
      enunciado: 'Qual é a metade de 3/4?',
      opcoes: ['1/4', '3/8', '6/4', '1/2'],
      resposta: '3/8',
      explicacao: 'A metade de 3/4 é (3/4) ÷ 2 = 3/8.',
      tags: ['frações', 'divisão de fração'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },
    {
      disciplina: 'matematica' as const,
      topico: 'Frações',
      subtopico: 'Adição de frações',
      nivel: 'E',
      dificuldade: 'medio' as const,
      tipo: 'numerico' as const,
      enunciado: 'Calcule: 1/3 + 1/6 = ?',
      opcoes: null,
      resposta: '1/2',
      explicacao: 'MMC(3,6) = 6. Então 1/3 = 2/6. Somando: 2/6 + 1/6 = 3/6 = 1/2.',
      tags: ['frações', 'adição de frações', 'MMC'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },
    {
      disciplina: 'matematica' as const,
      topico: 'Porcentagem',
      subtopico: 'Porcentagem básica',
      nivel: 'F',
      dificuldade: 'medio' as const,
      tipo: 'numerico' as const,
      enunciado: 'Quanto é 20% de 150?',
      opcoes: null,
      resposta: '30',
      explicacao: '20% de 150 = 0,20 × 150 = 30.',
      tags: ['porcentagem', 'básico'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },
    {
      disciplina: 'matematica' as const,
      topico: 'Porcentagem',
      subtopico: 'Desconto e acréscimo',
      nivel: 'G',
      dificuldade: 'dificil' as const,
      tipo: 'objetivo' as const,
      enunciado: 'Um produto custa R$ 200,00 e está com 15% de desconto. Qual é o preço final?',
      opcoes: ['R$ 170,00', 'R$ 180,00', 'R$ 185,00', 'R$ 160,00'],
      resposta: 'R$ 170,00',
      explicacao: 'Desconto = 15% × 200 = 30. Preço final = 200 − 30 = R$ 170,00.',
      tags: ['porcentagem', 'desconto', 'aplicação'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },
    {
      disciplina: 'matematica' as const,
      topico: 'Números',
      subtopico: 'Valor posicional',
      nivel: '2A',
      dificuldade: 'facil' as const,
      tipo: 'objetivo' as const,
      enunciado: 'No número 347, qual é o valor do algarismo 3?',
      opcoes: ['3', '30', '300', '3000'],
      resposta: '300',
      explicacao: 'O algarismo 3 ocupa a posição das centenas, portanto seu valor é 300.',
      tags: ['valor posicional', 'centenas', 'números'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },
    {
      disciplina: 'matematica' as const,
      topico: 'Geometria',
      subtopico: 'Área do retângulo',
      nivel: 'E',
      dificuldade: 'medio' as const,
      tipo: 'numerico' as const,
      enunciado: 'Um retângulo tem base 9 cm e altura 6 cm. Qual é sua área?',
      opcoes: null,
      resposta: '54',
      explicacao: 'Área = base × altura = 9 × 6 = 54 cm².',
      tags: ['geometria', 'área', 'retângulo'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },
    {
      disciplina: 'matematica' as const,
      topico: 'Álgebra',
      subtopico: 'Equações simples',
      nivel: 'F',
      dificuldade: 'dificil' as const,
      tipo: 'numerico' as const,
      enunciado: 'Resolva a equação: 3x + 5 = 20',
      opcoes: null,
      resposta: '5',
      explicacao: '3x = 20 − 5 = 15. Então x = 15 ÷ 3 = 5.',
      tags: ['álgebra', 'equação', 'primeiro grau'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },
    {
      disciplina: 'matematica' as const,
      topico: 'Medidas',
      subtopico: 'Conversão de unidades',
      nivel: 'D',
      dificuldade: 'medio' as const,
      tipo: 'numerico' as const,
      enunciado: 'Quantos centímetros há em 2,5 metros?',
      opcoes: null,
      resposta: '250',
      explicacao: '1 metro = 100 cm. Portanto 2,5 m = 2,5 × 100 = 250 cm.',
      tags: ['medidas', 'conversão', 'comprimento'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },
    {
      disciplina: 'matematica' as const,
      topico: 'Divisão',
      subtopico: 'Divisão com resto',
      nivel: 'C',
      dificuldade: 'medio' as const,
      tipo: 'objetivo' as const,
      enunciado: 'Qual é o resto da divisão de 29 por 4?',
      opcoes: ['0', '1', '2', '3'],
      resposta: '1',
      explicacao: '29 ÷ 4 = 7, com resto 1 (pois 4 × 7 = 28, e 29 − 28 = 1).',
      tags: ['divisão', 'resto', 'algoritmo'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },

    // ── Português ───────────────────────────────────────────────────────────────
    {
      disciplina: 'portugues' as const,
      topico: 'Ortografia',
      subtopico: 'Uso do S e Z',
      nivel: 'C',
      dificuldade: 'medio' as const,
      tipo: 'objetivo' as const,
      enunciado: 'Qual das alternativas está escrita corretamente?',
      opcoes: ['belesa', 'beleza', 'beleza', 'belessa'],
      resposta: 'beleza',
      explicacao: 'A palavra correta é "beleza", com Z, pois deriva de "belo" e segue a regra de sufixos -eza.',
      tags: ['ortografia', 'S e Z', 'sufixo'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },
    {
      disciplina: 'portugues' as const,
      topico: 'Pontuação',
      subtopico: 'Uso da vírgula',
      nivel: 'D',
      dificuldade: 'medio' as const,
      tipo: 'objetivo' as const,
      enunciado: 'Em qual frase a vírgula está usada corretamente?',
      opcoes: [
        'Comprei, pão leite e ovos.',
        'Comprei pão, leite e ovos.',
        'Comprei pão leite, e ovos.',
        'Comprei pão leite e, ovos.',
      ],
      resposta: 'Comprei pão, leite e ovos.',
      explicacao: 'A vírgula separa itens de uma enumeração. Antes do "e" final não se usa vírgula quando há apenas dois elementos ou quando a enumeração termina com "e".',
      tags: ['pontuação', 'vírgula', 'enumeração'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },
    {
      disciplina: 'portugues' as const,
      topico: 'Classes Gramaticais',
      subtopico: 'Substantivos',
      nivel: 'B',
      dificuldade: 'facil' as const,
      tipo: 'objetivo' as const,
      enunciado: 'Qual das palavras abaixo é um substantivo?',
      opcoes: ['correr', 'alegre', 'cidade', 'rapidamente'],
      resposta: 'cidade',
      explicacao: '"Cidade" é um substantivo porque nomeia um lugar. "Correr" é verbo, "alegre" é adjetivo e "rapidamente" é advérbio.',
      tags: ['classes gramaticais', 'substantivo', 'identificação'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },
    {
      disciplina: 'portugues' as const,
      topico: 'Classes Gramaticais',
      subtopico: 'Adjetivos',
      nivel: 'C',
      dificuldade: 'facil' as const,
      tipo: 'objetivo' as const,
      enunciado: 'Identifique o adjetivo na frase: "O menino inteligente resolveu a questão difícil."',
      opcoes: ['menino', 'resolveu', 'inteligente', 'questão'],
      resposta: 'inteligente',
      explicacao: '"Inteligente" e "difícil" são adjetivos. Na alternativa, "inteligente" é o adjetivo que caracteriza "menino".',
      tags: ['adjetivo', 'classes gramaticais'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },
    {
      disciplina: 'portugues' as const,
      topico: 'Interpretação de Texto',
      subtopico: 'Ideia principal',
      nivel: 'E',
      dificuldade: 'medio' as const,
      tipo: 'objetivo' as const,
      enunciado: 'Leia: "A leitura amplia o vocabulário, estimula a imaginação e desenvolve o raciocínio crítico." Qual é a ideia central do texto?',
      opcoes: [
        'A leitura serve apenas para aumentar o vocabulário.',
        'A leitura traz múltiplos benefícios cognitivos.',
        'O raciocínio crítico é mais importante que a imaginação.',
        'Ler é uma atividade difícil para a maioria das pessoas.',
      ],
      resposta: 'A leitura traz múltiplos benefícios cognitivos.',
      explicacao: 'O texto lista três benefícios da leitura (vocabulário, imaginação e raciocínio), expressando que ela é benéfica de várias formas.',
      tags: ['interpretação', 'ideia principal', 'leitura'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },
    {
      disciplina: 'portugues' as const,
      topico: 'Ortografia',
      subtopico: 'Acentuação',
      nivel: 'D',
      dificuldade: 'medio' as const,
      tipo: 'objetivo' as const,
      enunciado: 'Qual palavra está acentuada corretamente?',
      opcoes: ['cafe', 'café', 'cafè', 'cafê'],
      resposta: 'café',
      explicacao: '"Café" leva acento agudo no é porque é uma palavra oxítona terminada em vogal aberta acentuável.',
      tags: ['acentuação', 'acento agudo', 'oxítona'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },
    {
      disciplina: 'portugues' as const,
      topico: 'Morfologia',
      subtopico: 'Plural de substantivos',
      nivel: 'B',
      dificuldade: 'facil' as const,
      tipo: 'objetivo' as const,
      enunciado: 'Qual é o plural correto de "cidadão"?',
      opcoes: ['cidadãos', 'cidadões', 'cidadães', 'cidadãs'],
      resposta: 'cidadãos',
      explicacao: 'O plural de "cidadão" é "cidadãos". Palavras terminadas em -ão podem ter plural em -ãos, -ões ou -ães. "Cidadão" segue o padrão -ãos.',
      tags: ['plural', 'morfologia', 'terminação ão'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },
    {
      disciplina: 'portugues' as const,
      topico: 'Sintaxe',
      subtopico: 'Sujeito e predicado',
      nivel: 'D',
      dificuldade: 'medio' as const,
      tipo: 'objetivo' as const,
      enunciado: 'Na frase "Os alunos estudaram muito.", qual é o sujeito?',
      opcoes: ['Os alunos', 'estudaram', 'muito', 'estudaram muito'],
      resposta: 'Os alunos',
      explicacao: 'O sujeito é "Os alunos", pois é o núcleo sobre o qual se faz a declaração (predicado: estudaram muito).',
      tags: ['sintaxe', 'sujeito', 'predicado'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },
    {
      disciplina: 'portugues' as const,
      topico: 'Coesão',
      subtopico: 'Conectivos',
      nivel: 'F',
      dificuldade: 'dificil' as const,
      tipo: 'objetivo' as const,
      enunciado: 'Escolha o conectivo adequado: "Ele estudou muito, ___ não passou na prova."',
      opcoes: ['portanto', 'pois', 'porém', 'logo'],
      resposta: 'porém',
      explicacao: '"Porém" indica adversidade/contraste: estudou muito (causa esperada), mas não passou (resultado contrário ao esperado).',
      tags: ['coesão', 'conectivos', 'adversidade'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },
    {
      disciplina: 'portugues' as const,
      topico: 'Semântica',
      subtopico: 'Sinônimos',
      nivel: 'C',
      dificuldade: 'facil' as const,
      tipo: 'objetivo' as const,
      enunciado: 'Qual é o sinônimo de "feliz"?',
      opcoes: ['triste', 'alegre', 'bravo', 'cansado'],
      resposta: 'alegre',
      explicacao: '"Alegre" tem sentido semelhante a "feliz", ambos expressam um estado positivo de ânimo.',
      tags: ['semântica', 'sinônimos', 'vocabulário'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },
    {
      disciplina: 'portugues' as const,
      topico: 'Interpretação de Texto',
      subtopico: 'Inferência',
      nivel: 'G',
      dificuldade: 'dificil' as const,
      tipo: 'texto' as const,
      enunciado: 'Leia: "João sempre chegava ao trabalho antes de todos. Naquele dia, porém, seu despertador não tocou." Explique o que provavelmente aconteceu com João naquele dia.',
      opcoes: null,
      resposta: 'João chegou atrasado ao trabalho porque seu despertador não tocou e ele dormiu mais do que o previsto.',
      explicacao: 'A inferência indica que sem o despertador, João provavelmente não acordou no horário habitual e chegou atrasado — contrariando seu hábito.',
      tags: ['inferência', 'interpretação', 'texto narrativo'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },
    {
      disciplina: 'portugues' as const,
      topico: 'Ortografia',
      subtopico: 'Uso do H inicial',
      nivel: 'B',
      dificuldade: 'facil' as const,
      tipo: 'objetivo' as const,
      enunciado: 'Qual palavra começa com H mas o H é mudo?',
      opcoes: ['hora', 'harpa', 'húmus', 'hélice'],
      resposta: 'hora',
      explicacao: 'Em "hora", o H é mudo — pronunciamos apenas "ora". Nas demais, o H também é mudo, mas "hora" é a resposta mais comum e usada no cotidiano.',
      tags: ['ortografia', 'h mudo', 'fonética'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },

    // ── Inglês ───────────────────────────────────────────────────────────────────
    {
      disciplina: 'ingles' as const,
      topico: 'Verb To Be',
      subtopico: 'Afirmativa',
      nivel: '2A',
      dificuldade: 'facil' as const,
      tipo: 'objetivo' as const,
      enunciado: 'Complete the sentence: "She ___ a teacher."',
      opcoes: ['am', 'is', 'are', 'be'],
      resposta: 'is',
      explicacao: 'With the pronoun "she" (third person singular), we use "is". She is a teacher.',
      tags: ['verb to be', 'is', 'present simple'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },
    {
      disciplina: 'ingles' as const,
      topico: 'Verb To Be',
      subtopico: 'Negativa',
      nivel: '2A',
      dificuldade: 'facil' as const,
      tipo: 'objetivo' as const,
      enunciado: 'Which sentence is correct in the negative form? "They ___ happy."',
      opcoes: ['are not', 'is not', 'am not', 'be not'],
      resposta: 'are not',
      explicacao: '"They" uses "are". Negative: They are not happy. (or They aren\'t happy.)',
      tags: ['verb to be', 'negative', 'are'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },
    {
      disciplina: 'ingles' as const,
      topico: 'Simple Present',
      subtopico: 'Third person singular',
      nivel: 'A',
      dificuldade: 'medio' as const,
      tipo: 'objetivo' as const,
      enunciado: 'Choose the correct form: "He ___ to school every day."',
      opcoes: ['go', 'goes', 'going', 'gone'],
      resposta: 'goes',
      explicacao: 'In the Simple Present, third person singular (he/she/it) adds -s or -es to the verb. "go" → "goes".',
      tags: ['simple present', 'third person', 'conjugation'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },
    {
      disciplina: 'ingles' as const,
      topico: 'Simple Present',
      subtopico: 'Interrogativa',
      nivel: 'A',
      dificuldade: 'medio' as const,
      tipo: 'objetivo' as const,
      enunciado: 'How do you form a yes/no question in Simple Present with "she likes pizza"?',
      opcoes: [
        'She likes pizza?',
        'Does she likes pizza?',
        'Does she like pizza?',
        'Do she like pizza?',
      ],
      resposta: 'Does she like pizza?',
      explicacao: 'For questions with he/she/it, use "Does" + subject + base verb (no -s). Does she like pizza?',
      tags: ['simple present', 'question', 'does'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },
    {
      disciplina: 'ingles' as const,
      topico: 'Vocabulary',
      subtopico: 'Colors',
      nivel: '4A',
      dificuldade: 'facil' as const,
      tipo: 'objetivo' as const,
      enunciado: 'What color is the sky on a clear day?',
      opcoes: ['green', 'red', 'blue', 'yellow'],
      resposta: 'blue',
      explicacao: 'The sky on a clear day is blue.',
      tags: ['vocabulary', 'colors', 'basic'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },
    {
      disciplina: 'ingles' as const,
      topico: 'Vocabulary',
      subtopico: 'Numbers',
      nivel: '5A',
      dificuldade: 'facil' as const,
      tipo: 'objetivo' as const,
      enunciado: 'How do you say "15" in English?',
      opcoes: ['fifty', 'fifteen', 'fiveteen', 'fiften'],
      resposta: 'fifteen',
      explicacao: '"15" in English is "fifteen". Note: not "fiveteen" — the correct spelling is "fifteen".',
      tags: ['vocabulary', 'numbers', 'spelling'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },
    {
      disciplina: 'ingles' as const,
      topico: 'Reading Comprehension',
      subtopico: 'Short texts',
      nivel: 'B',
      dificuldade: 'medio' as const,
      tipo: 'objetivo' as const,
      enunciado: 'Read: "Tom wakes up at 7 am. He eats breakfast and goes to school." What does Tom do first after waking up?',
      opcoes: ['He goes to school.', 'He eats breakfast.', 'He watches TV.', 'He sleeps more.'],
      resposta: 'He eats breakfast.',
      explicacao: 'According to the text, after waking up Tom "eats breakfast" and then goes to school.',
      tags: ['reading comprehension', 'daily routine', 'sequence'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },
    {
      disciplina: 'ingles' as const,
      topico: 'Vocabulary',
      subtopico: 'Family members',
      nivel: '3A',
      dificuldade: 'facil' as const,
      tipo: 'objetivo' as const,
      enunciado: 'What is the English word for "irmã"?',
      opcoes: ['brother', 'mother', 'sister', 'daughter'],
      resposta: 'sister',
      explicacao: '"Sister" means "irmã" in Portuguese. "Brother" = irmão, "mother" = mãe, "daughter" = filha.',
      tags: ['vocabulary', 'family', 'translation'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },
    {
      disciplina: 'ingles' as const,
      topico: 'Simple Present',
      subtopico: 'Frequência',
      nivel: 'B',
      dificuldade: 'medio' as const,
      tipo: 'objetivo' as const,
      enunciado: 'Which adverb of frequency means "quase sempre"?',
      opcoes: ['never', 'sometimes', 'usually', 'always'],
      resposta: 'usually',
      explicacao: '"Usually" means "quase sempre / geralmente". Always = sempre, sometimes = às vezes, never = nunca.',
      tags: ['adverbs of frequency', 'simple present', 'vocabulary'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },
    {
      disciplina: 'ingles' as const,
      topico: 'Reading Comprehension',
      subtopico: 'Identifying information',
      nivel: 'C',
      dificuldade: 'dificil' as const,
      tipo: 'texto' as const,
      enunciado: 'Read: "Maria is 12 years old. She lives in São Paulo and loves reading books. Her favorite subject is science." Write two facts about Maria.',
      opcoes: null,
      resposta: 'Maria is 12 years old and she loves reading books. (accept any two correct facts from the text)',
      explicacao: 'The text gives three facts: age (12), location (São Paulo), and interests (reading, science). Any two are correct.',
      tags: ['reading', 'facts', 'information retrieval'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },
    {
      disciplina: 'ingles' as const,
      topico: 'Vocabulary',
      subtopico: 'Days of the week',
      nivel: '4A',
      dificuldade: 'facil' as const,
      tipo: 'objetivo' as const,
      enunciado: 'What day comes after Wednesday?',
      opcoes: ['Tuesday', 'Thursday', 'Friday', 'Monday'],
      resposta: 'Thursday',
      explicacao: 'The days of the week: Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday. Thursday comes after Wednesday.',
      tags: ['vocabulary', 'days of the week', 'sequence'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },
    {
      disciplina: 'ingles' as const,
      topico: 'Verb To Be',
      subtopico: 'Interrogativa',
      nivel: '2A',
      dificuldade: 'facil' as const,
      tipo: 'objetivo' as const,
      enunciado: 'How do you ask "Você é estudante?" in English?',
      opcoes: [
        'You are a student?',
        'Are you a student?',
        'Is you a student?',
        'Do you are a student?',
      ],
      resposta: 'Are you a student?',
      explicacao: 'Questions with "to be" invert the subject and verb: Are + you + complement?',
      tags: ['verb to be', 'question', 'are'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },
    {
      disciplina: 'ingles' as const,
      topico: 'Simple Present',
      subtopico: 'Negativa',
      nivel: 'A',
      dificuldade: 'medio' as const,
      tipo: 'objetivo' as const,
      enunciado: 'Make the sentence negative: "I like chocolate."',
      opcoes: [
        'I not like chocolate.',
        'I do not like chocolate.',
        'I does not like chocolate.',
        'I am not like chocolate.',
      ],
      resposta: 'I do not like chocolate.',
      explicacao: 'Negative in Simple Present: subject + do/does + not + base verb. For I/you/we/they use "do not".',
      tags: ['simple present', 'negative', 'do not'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },
    {
      disciplina: 'ingles' as const,
      topico: 'Vocabulary',
      subtopico: 'Animals',
      nivel: '5A',
      dificuldade: 'facil' as const,
      tipo: 'objetivo' as const,
      enunciado: 'What is the English word for "cachorro"?',
      opcoes: ['cat', 'dog', 'bird', 'fish'],
      resposta: 'dog',
      explicacao: '"Dog" means "cachorro". Cat = gato, bird = pássaro, fish = peixe.',
      tags: ['vocabulary', 'animals', 'translation'],
      origem: 'manual' as const,
      status: 'publicado' as const,
    },
  ]

  let criados = 0
  for (const ex of bibExercicios) {
    const existente = await prisma.bibExercicio.findFirst({
      where: { enunciado: ex.enunciado },
    })
    if (!existente) {
      await prisma.bibExercicio.create({
        data: {
          ...ex,
          opcoes: ex.opcoes ?? undefined,
          criadoPorId: franqueado.id,
        },
      })
      criados++
    }
  }

  console.log(`Biblioteca: ${criados} exercícios criados (${bibExercicios.length - criados} já existiam).`)
  console.log('Seed concluído.')
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
